package command

import (
	"fmt"
	"os"
	"strings"

	"github.com/sshm/sshm/internal/config"
	"github.com/sshm/sshm/internal/ui"
)

func (app *App) cmdExportSSHConfig(args []string) error {
	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	outPath := config.SSHConfigPath()
	if len(args) > 0 {
		outPath = args[0]
	}

	var lines []string
	lines = append(lines, "# Generated by sshm - DO NOT EDIT MANUALLY")
	lines = append(lines, "# Source: "+app.Store.Path())
	lines = append(lines, "")

	for _, h := range hf.Hosts {
		lines = append(lines, fmt.Sprintf("Host %s", h.Alias))
		lines = append(lines, fmt.Sprintf("    HostName %s", h.Host))
		lines = append(lines, fmt.Sprintf("    User %s", h.User))
		lines = append(lines, fmt.Sprintf("    Port %d", h.Port))
		if h.Identity != "" {
			identityPath := config.ExpandPath(h.Identity)
			lines = append(lines, fmt.Sprintf("    IdentityFile %s", identityPath))
		}
		lines = append(lines, "")
	}

	content := strings.Join(lines, "\n")
	if err := os.WriteFile(outPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("写入 SSH 配置失败: %w", err)
	}

	ui.PrintSuccess("SSH 配置已导出到: %s", outPath)
	fmt.Println()
	fmt.Println("  使用方式：")
	fmt.Println(fmt.Sprintf("    ssh -F %s <别名>", outPath))
	fmt.Println()
	return nil
}

func (app *App) cmdImportSSHConfig(args []string) error {
	srcPath := ""
	if len(args) > 0 {
		srcPath = args[0]
	} else {
		srcPath = ui.ReadLine("请输入 SSH 配置文件路径 [~/.ssh/config]: ")
		if srcPath == "" {
			home, _ := os.UserHomeDir()
			srcPath = home + "/.ssh/config"
		}
	}

	data, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("读取 SSH 配置失败: %w", err)
	}

	hosts := parseSSHConfig(string(data))
	if len(hosts) == 0 {
		ui.PrintWarn("未找到 Host 条目")
		return nil
	}

	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	imported := 0
	for _, h := range hosts {
		// Check if alias already exists
		exists := false
		for _, existing := range hf.Hosts {
			if existing.Alias == h.Alias {
				exists = true
				break
			}
		}
		if exists {
			ui.PrintWarn("别名 %s 已存在，跳过", h.Alias)
			continue
		}
		h.Auth = "auto"
		hf.Hosts = append(hf.Hosts, h)
		imported++
	}

	if imported > 0 {
		if err := app.Store.Save(hf); err != nil {
			return fmt.Errorf("保存配置失败: %w", err)
		}
		ui.PrintSuccess("已从 SSH 配置导入 %d 台主机", imported)
	} else {
		ui.PrintWarn("没有新主机可导入")
	}

	return nil
}

// parseSSHConfig parses an OpenSSH config file and returns Host entries.
func parseSSHConfig(content string) []config.Host {
	var hosts []config.Host
	lines := strings.Split(content, "\n")

	var current *config.Host
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}

		keyword := strings.ToLower(parts[0])
		value := strings.Join(parts[1:], " ")

		switch keyword {
		case "host":
			if current != nil && current.Alias != "" {
				hosts = append(hosts, *current)
			}
			// Skip wildcard hosts
			if strings.Contains(value, "*") || strings.Contains(value, "?") {
				current = nil
				continue
			}
			current = &config.Host{
				Alias: value,
				Port:  22,
				Auth:  "auto",
			}
		case "hostname":
			if current != nil {
				current.Host = value
			}
		case "user":
			if current != nil {
				current.User = value
			}
		case "port":
			if current != nil {
				fmt.Sscanf(value, "%d", &current.Port)
			}
		case "identityfile":
			if current != nil {
				current.Identity = value
			}
		}
	}

	if current != nil && current.Alias != "" && current.Host != "" {
		hosts = append(hosts, *current)
	}

	return hosts
}
