package command

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/fanhuadesenlinnn/sshmd/v6/internal/config"
	"github.com/fanhuadesenlinnn/sshmd/v6/internal/safefile"
	"github.com/fanhuadesenlinnn/sshmd/v6/internal/shellquote"
	"github.com/fanhuadesenlinnn/sshmd/v6/internal/ui"
)

func (app *App) cmdExportSSHConfig(args []string) error {
	force := false
	var positionals []string
	for _, arg := range args {
		if arg == "--force" {
			force = true
			continue
		}
		positionals = append(positionals, arg)
	}
	if len(positionals) != 1 {
		return fmt.Errorf("用法: sshmd export-ssh-config [--force] <输出文件>")
	}
	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	outPath := config.ExpandPath(positionals[0])
	if !force {
		if _, statErr := os.Lstat(outPath); statErr == nil {
			return fmt.Errorf("输出文件已存在，拒绝覆盖: %s（确认后使用 --force）", outPath)
		} else if !os.IsNotExist(statErr) {
			return fmt.Errorf("检查输出文件失败: %w", statErr)
		}
	}

	var lines []string
	lines = append(lines, "# Generated by sshmd - DO NOT EDIT MANUALLY")
	lines = append(lines, "# Source: "+app.Store.Path())
	lines = append(lines, "")

	for _, h := range hf.Hosts {
		lines = append(lines, fmt.Sprintf("Host %s", h.Alias))
		lines = append(lines, fmt.Sprintf("    HostName %s", h.Host))
		lines = append(lines, fmt.Sprintf("    User %s", h.User))
		lines = append(lines, fmt.Sprintf("    Port %d", h.Port))
		if h.Identity != "" {
			if _, managed := config.ManagedKeyName(h.Identity); managed {
				lines = append(lines, "    # Managed key is available only through sshmd")
			} else {
				lines = append(lines, fmt.Sprintf("    IdentityFile %s", h.Identity))
			}
		}
		if h.JumpHost != "" {
			lines = append(lines, fmt.Sprintf("    ProxyJump %s", h.JumpHost))
		}
		lines = append(lines, "")
	}

	content := strings.Join(lines, "\n")
	if err := safefile.Write(outPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("写入 SSH 配置失败: %w", err)
	}

	ui.PrintSuccess("SSH 配置已导出到: %s", outPath)
	fmt.Println()
	fmt.Println("  使用方式：")
	fmt.Printf("    ssh -F %s <别名>\n", outPath)
	fmt.Println()
	return nil
}

func (app *App) cmdImportSSHConfig(args []string) error {
	if len(args) > 1 {
		return fmt.Errorf("用法: sshmd import-ssh-config [SSH 配置路径]")
	}
	srcPath := ""
	if len(args) > 0 {
		srcPath = args[0]
	} else {
		srcPath = ui.ReadLine("请输入 SSH 配置文件路径 [~/.ssh/config]: ")
		if srcPath == "" {
			home, _ := os.UserHomeDir()
			srcPath = home + "/.ssh/config"
		}
	}

	srcPath = config.ExpandPath(srcPath)
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("读取 SSH 配置失败: %w", err)
	}

	hosts := parseSSHConfig(string(data))
	if len(hosts) == 0 {
		ui.PrintWarn("未找到 Host 条目")
		return nil
	}

	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	type identityFollowup struct {
		path    string
		keyName string
		aliases []string
	}
	usedKeyNames := make(map[string]bool)
	doc, err := app.Store.Repository().Load()
	if err != nil {
		return err
	}
	for _, key := range doc.ManagedKeys.Keys {
		usedKeyNames[key.Name] = true
	}
	identityByPath := make(map[string]int)
	var identityFollowups []identityFollowup
	importStart := len(hf.Hosts)
	imported := 0
	for _, h := range hosts {
		// Check if alias already exists
		exists := false
		for _, existing := range hf.Hosts {
			if existing.Alias == h.Alias {
				exists = true
				break
			}
		}
		if exists {
			ui.PrintWarn("别名 %s 已存在，跳过", h.Alias)
			continue
		}
		identityPath := h.Identity
		h.Identity = ""
		if errs := h.Validate(); len(errs) > 0 {
			ui.PrintWarn("主机 %s 配置无效，跳过: %s", h.Alias, strings.Join(errs, "; "))
			continue
		}
		hf.Hosts = append(hf.Hosts, h)
		if identityPath != "" {
			if index, ok := identityByPath[identityPath]; ok {
				identityFollowups[index].aliases = append(identityFollowups[index].aliases, h.Alias)
			} else {
				keyName := availableImportedKeyName(h.Alias, usedKeyNames)
				identityByPath[identityPath] = len(identityFollowups)
				identityFollowups = append(identityFollowups, identityFollowup{
					path: identityPath, keyName: keyName, aliases: []string{h.Alias},
				})
			}
		}
		imported++
	}

	if imported > 0 {
		jumpWarnings := sanitizeImportedJumpHosts(hf, importStart)
		if err := app.Store.Save(hf); err != nil {
			return fmt.Errorf("保存配置失败: %w", err)
		}
		ui.PrintSuccess("已从 SSH 配置导入 %d 台主机", imported)
		for _, warning := range jumpWarnings {
			ui.PrintWarn("%s", warning)
		}
		for _, followup := range identityFollowups {
			ui.PrintWarn("主机 %s 的 IdentityFile 未直接写入 sshmd；主机元数据已导入，identity 已清空", strings.Join(followup.aliases, ", "))
		}
		if len(identityFollowups) > 0 {
			fmt.Println()
			fmt.Println("  继续导入并绑定私钥（可直接执行）:")
			for _, followup := range identityFollowups {
				fmt.Printf("    sshmd key import %s %s\n", shellquote.Single(followup.keyName), shellquote.Single(followup.path))
				fmt.Printf("    sshmd key use %s", shellquote.Single(followup.keyName))
				for _, alias := range followup.aliases {
					fmt.Printf(" %s", shellquote.Single(alias))
				}
				fmt.Println()
			}
			fmt.Println()
		}
	} else {
		ui.PrintWarn("没有新主机可导入")
	}

	return nil
}

func sanitizeImportedJumpHosts(hf *config.HostsFile, start int) []string {
	byAlias := make(map[string]*config.Host, len(hf.Hosts))
	for i := range hf.Hosts {
		byAlias[hf.Hosts[i].Alias] = &hf.Hosts[i]
	}

	var warnings []string
	for i := start; i < len(hf.Hosts); i++ {
		host := &hf.Hosts[i]
		jump := strings.TrimSpace(host.JumpHost)
		host.JumpHost = jump
		switch {
		case jump == "", strings.EqualFold(jump, "none"):
			host.JumpHost = ""
		case config.ValidateHostAlias(jump) != nil:
			warnings = append(warnings, fmt.Sprintf("主机 %s 的 ProxyJump %q 无法映射为 sshmd 单级跳板机别名，已清空", host.Alias, jump))
			host.JumpHost = ""
		case jump == host.Alias:
			warnings = append(warnings, fmt.Sprintf("主机 %s 不能将自身作为跳板机，ProxyJump 已清空", host.Alias))
			host.JumpHost = ""
		case byAlias[jump] == nil:
			warnings = append(warnings, fmt.Sprintf("主机 %s 的 ProxyJump 引用了未导入的别名 %s，已清空", host.Alias, jump))
			host.JumpHost = ""
		}
	}

	// sshmd 只支持单级跳板；使用清理后的快照避免循环或导入顺序影响结果。
	targetHasJump := make(map[string]bool, len(hf.Hosts))
	for i := range hf.Hosts {
		targetHasJump[hf.Hosts[i].Alias] = hf.Hosts[i].JumpHost != ""
	}
	for i := start; i < len(hf.Hosts); i++ {
		host := &hf.Hosts[i]
		if host.JumpHost != "" && targetHasJump[host.JumpHost] {
			warnings = append(warnings, fmt.Sprintf("主机 %s 的 ProxyJump 指向了同样使用跳板机的 %s，sshmd 仅支持单级跳板，已清空", host.Alias, host.JumpHost))
			host.JumpHost = ""
		}
	}
	return warnings
}

func availableImportedKeyName(alias string, used map[string]bool) string {
	base := alias + "-key"
	name := base
	for suffix := 2; used[name]; suffix++ {
		name = fmt.Sprintf("%s-%d", base, suffix)
	}
	used[name] = true
	return name
}

type sshConfigBlock struct {
	patterns []string
	values   map[string]string
}

// parseSSHConfig imports literal aliases while resolving the supported
// OpenSSH options with its first-obtained-value semantics. Wildcard Host
// blocks (especially the common trailing `Host *`) provide defaults without
// becoming imported aliases themselves.
func parseSSHConfig(content string) []config.Host {
	defaultUser := os.Getenv("USER")
	if defaultUser == "" {
		defaultUser = "root"
	}
	current := &sshConfigBlock{patterns: []string{"*"}, values: map[string]string{}}
	var blocks []sshConfigBlock
	var aliases []string
	seenAliases := map[string]bool{}
	flush := func() {
		if current != nil && len(current.values) > 0 {
			blocks = append(blocks, *current)
		}
	}

	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}

		keyword := strings.ToLower(parts[0])
		value := strings.Trim(strings.Join(parts[1:], " "), `"'`)

		switch keyword {
		case "host":
			flush()
			patterns := make([]string, 0, len(parts)-1)
			for _, pattern := range parts[1:] {
				pattern = strings.Trim(pattern, `"'`)
				if pattern == "" {
					continue
				}
				patterns = append(patterns, pattern)
				if !strings.HasPrefix(pattern, "!") && !strings.ContainsAny(pattern, "*?[") && !seenAliases[pattern] {
					seenAliases[pattern] = true
					aliases = append(aliases, pattern)
				}
			}
			current = &sshConfigBlock{patterns: patterns, values: map[string]string{}}
		case "match":
			// Match conditions can depend on runtime state sshmd does not model.
			// Stop applying that section until the next Host block.
			flush()
			current = nil
		case "hostname", "user", "port", "identityfile", "proxyjump":
			if current != nil {
				if _, alreadySet := current.values[keyword]; !alreadySet {
					current.values[keyword] = value
				}
			}
		}
	}
	flush()

	hosts := make([]config.Host, 0, len(aliases))
	for _, alias := range aliases {
		resolved := map[string]string{}
		for _, block := range blocks {
			if !sshConfigBlockMatches(block.patterns, alias) {
				continue
			}
			for key, value := range block.values {
				if _, exists := resolved[key]; !exists {
					resolved[key] = value
				}
			}
		}
		host := config.DefaultHost()
		host.ID = config.NewID()
		host.Alias = alias
		host.Host = alias
		host.User = defaultUser
		if value, ok := resolved["hostname"]; ok && value != "" {
			host.Host = value
		}
		if value, ok := resolved["user"]; ok && value != "" {
			host.User = value
		}
		if value, ok := resolved["port"]; ok {
			host.Port = 0
			_, _ = fmt.Sscanf(value, "%d", &host.Port)
		}
		host.Identity = resolved["identityfile"]
		host.JumpHost = resolved["proxyjump"]
		hosts = append(hosts, host)
	}
	return hosts
}

func sshConfigBlockMatches(patterns []string, alias string) bool {
	matched := false
	alias = strings.ToLower(alias)
	for _, raw := range patterns {
		negated := strings.HasPrefix(raw, "!")
		pattern := strings.TrimPrefix(raw, "!")
		current, err := path.Match(strings.ToLower(pattern), alias)
		if err != nil {
			current = strings.EqualFold(pattern, alias)
		}
		if negated && current {
			return false
		}
		if !negated && current {
			matched = true
		}
	}
	return matched
}
