package command

import (
	"fmt"
	"os"
	"strings"

	"github.com/fanhuadesenlinnn/sshm/v6/internal/config"
	"github.com/fanhuadesenlinnn/sshm/v6/internal/safefile"
	"github.com/fanhuadesenlinnn/sshm/v6/internal/ui"
)

func (app *App) cmdExportSSHConfig(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("用法: sshm export-ssh-config <输出文件>")
	}
	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	outPath := config.ExpandPath(args[0])

	var lines []string
	lines = append(lines, "# Generated by sshm - DO NOT EDIT MANUALLY")
	lines = append(lines, "# Source: "+app.Store.Path())
	lines = append(lines, "")

	for _, h := range hf.Hosts {
		lines = append(lines, fmt.Sprintf("Host %s", h.Alias))
		lines = append(lines, fmt.Sprintf("    HostName %s", h.Host))
		lines = append(lines, fmt.Sprintf("    User %s", h.User))
		lines = append(lines, fmt.Sprintf("    Port %d", h.Port))
		if h.Identity != "" {
			if _, managed := config.ManagedKeyName(h.Identity); managed {
				lines = append(lines, "    # Managed key is available only through sshm")
			}
		}
		lines = append(lines, "")
	}

	content := strings.Join(lines, "\n")
	if err := safefile.Write(outPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("写入 SSH 配置失败: %w", err)
	}

	ui.PrintSuccess("SSH 配置已导出到: %s", outPath)
	fmt.Println()
	fmt.Println("  使用方式：")
	fmt.Printf("    ssh -F %s <别名>\n", outPath)
	fmt.Println()
	return nil
}

func (app *App) cmdImportSSHConfig(args []string) error {
	srcPath := ""
	if len(args) > 0 {
		srcPath = args[0]
	} else {
		srcPath = ui.ReadLine("请输入 SSH 配置文件路径 [~/.ssh/config]: ")
		if srcPath == "" {
			home, _ := os.UserHomeDir()
			srcPath = home + "/.ssh/config"
		}
	}

	srcPath = config.ExpandPath(srcPath)
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("读取 SSH 配置失败: %w", err)
	}

	hosts := parseSSHConfig(string(data))
	if len(hosts) == 0 {
		ui.PrintWarn("未找到 Host 条目")
		return nil
	}

	hf, err := app.Store.Load()
	if err != nil {
		return err
	}

	imported := 0
	for _, h := range hosts {
		if h.Identity != "" {
			ui.PrintWarn("主机 %s 引用了 IdentityFile，跳过；请先使用 sshm key import 明确导入私钥", h.Alias)
			continue
		}
		// Check if alias already exists
		exists := false
		for _, existing := range hf.Hosts {
			if existing.Alias == h.Alias {
				exists = true
				break
			}
		}
		if exists {
			ui.PrintWarn("别名 %s 已存在，跳过", h.Alias)
			continue
		}
		if errs := h.Validate(); len(errs) > 0 {
			ui.PrintWarn("主机 %s 配置无效，跳过: %s", h.Alias, strings.Join(errs, "; "))
			continue
		}
		hf.Hosts = append(hf.Hosts, h)
		imported++
	}

	if imported > 0 {
		if err := app.Store.Save(hf); err != nil {
			return fmt.Errorf("保存配置失败: %w", err)
		}
		ui.PrintSuccess("已从 SSH 配置导入 %d 台主机", imported)
	} else {
		ui.PrintWarn("没有新主机可导入")
	}

	return nil
}

// parseSSHConfig parses an OpenSSH config file and returns Host entries.
func parseSSHConfig(content string) []config.Host {
	var hosts []config.Host
	lines := strings.Split(content, "\n")
	defaultUser := os.Getenv("USER")
	if defaultUser == "" {
		defaultUser = "root"
	}

	var aliases []string
	current := config.DefaultHost()
	current.Host = ""
	current.User = defaultUser
	flush := func() {
		for _, alias := range aliases {
			h := current
			h.ID = config.NewID()
			h.Alias = alias
			if h.Host == "" {
				h.Host = alias
			}
			hosts = append(hosts, h)
		}
		aliases = nil
		current = config.DefaultHost()
		current.Host = ""
		current.User = defaultUser
	}

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}

		keyword := strings.ToLower(parts[0])
		value := strings.Trim(strings.Join(parts[1:], " "), `"'`)

		switch keyword {
		case "host":
			flush()
			for _, alias := range parts[1:] {
				alias = strings.Trim(alias, `"'`)
				if !strings.ContainsAny(alias, "*?!") {
					aliases = append(aliases, alias)
				}
			}
		case "hostname":
			if len(aliases) > 0 {
				current.Host = value
			}
		case "user":
			if len(aliases) > 0 {
				current.User = value
			}
		case "port":
			if len(aliases) > 0 {
				_, _ = fmt.Sscanf(value, "%d", &current.Port)
			}
		case "identityfile":
			if len(aliases) > 0 {
				current.Identity = value
			}
		}
	}

	flush()
	return hosts
}
